export default defineAppConfig({
  ui: {
    colors: {
      primary: "black",
      neutral: "neutral",
    },
    input: {
      slots: { root: "w-full" },
    },
    textarea: {
      slots: { root: "w-full" },
    },
    button: {
      slots: { base: "cursor-pointer rounded-md font-medium" },
      defaultVariants: {
        size: "sm",
        color: "neutral",
      },
    },
    tabs: {
      slots: { trigger: "cursor-pointer" },
    },
    select: {
      slots: { root: "w-full", base: "w-full cursor-pointer" },
    },
    selectMenu: {
      slots: { root: "w-full", base: "w-full cursor-pointer" },
    },
    icons: {
      arrowDown: "i-solar-arrow-down-linear",
      arrowLeft: "i-solar-arrow-left-linear",
      arrowRight: "i-solar-arrow-right-linear",
      arrowUp: "i-solar-arrow-up-linear",
      caution: "i-solar-danger-square-linear",
      check: "i-solar-check-circle-linear",
      chevronDoubleLeft: "i-solar-double-alt-arrow-left-linear",
      chevronDoubleRight: "i-solar-double-alt-arrow-right-linear",
      chevronDown: "i-solar-alt-arrow-down-linear",
      chevronLeft: "i-solar-alt-arrow-left-linear",
      chevronRight: "i-solar-alt-arrow-right-linear",
      chevronUp: "i-solar-alt-arrow-up-linear",
      close: "i-solar-close-circle-linear",
      copy: "i-solar-copy-linear",
      copyCheck: "i-solar-clipboard-check-linear",
      dark: "i-solar-moon-linear",
      drag: "i-solar-reorder-linear",
      ellipsis: "i-solar-menu-dots-linear",
      error: "i-solar-close-square-linear",
      external: "i-solar-square-arrow-right-up-linear",
      eye: "i-solar-eye-linear",
      eyeOff: "i-solar-eye-closed-linear",
      file: "i-solar-file-linear",
      folder: "i-solar-folder-linear",
      folderOpen: "i-solar-folder-open-linear",
      hash: "i-solar-hashtag-linear",
      info: "i-solar-info-square-linear",
      light: "i-solar-sun-linear",
      loading: "i-solar-refresh-linear",
      menu: "i-solar-hamburger-menu-linear",
      minus: "i-solar-minus-square-linear",
      panelClose: "i-solar-sidebar-minimalistic-linear",
      panelOpen: "i-solar-sidebar-minimalistic-linear",
      plus: "i-solar-add-square-linear",
      reload: "i-solar-restart-linear",
      search: "i-solar-magnifer-linear",
      stop: "i-solar-stop-linear",
      success: "i-solar-check-square-linear",
      system: "i-solar-monitor-linear",
      tip: "i-solar-lightbulb-linear",
      upload: "i-solar-upload-linear",
      warning: "i-solar-danger-triangle-linear",
    },
  },
});
