export interface MacroImage {
  dir_id: number;
  dir_name: string;
  file_id: number;
  file_name: string;
  file_ext: string;
  file_url: string;
  is_title: number;
  img_type: string;
}

export interface MacroImageFolder {
  id: number;
  name: string;
  images: MacroImage[];
}

export interface MacroFlat {
  id: number;
  type: string;
  activity: string;
  category: string;
  is_published: number;
  is_purchase: number;
  status: number;
  status_name: string;
  status_real: number;
  status_real_name: string;
  is_reserved: number;
  parent_id: number;
  complex_id: number;
  has_parent_id: number;
  date_modified: number;
  promos: number[];
  promo_max_discount: unknown[];
  company_id: number;
  company_name: string;
  company_url: string;
  company_web: string;
  company_role: string;
  company_email: string;
  company_original_id: number;
  contacts_sell_name: string;
  contacts_sell_first_name: string;
  contacts_sell_last_name: string;
  contacts_sell_middle_name: string;
  contacts_sell_id: number;
  contacts_sell_inn: string;
  contacts_sell_type: number;
  title: string;
  title_minimal: string;
  is_hot: number;
  is_advert: number;
  is_sold: number;
  export_reserved: number;
  description: string;
  developer_description: string;
  category_name: string;
  date_published: number;
  date_added: number;
  manager_name: string;
  manager_phones: string;
  sales_phones?: unknown;
  sales_department_phone?: unknown;
  export_phone?: unknown;
  company_phone: string;
  disallow_messages?: unknown;
  manager_avatar: string;
  address: string;
  parent_address: string;
  parent_address_short: string;
  house_title: string;
  images: MacroImageFolder[];
  images_wo_parent: unknown[];
  title_image_id: number;
  title_image: string;
  title_image_dir_name: string;
  export_url?: unknown;
  parent_tags: string;
  tags: string;
  restoration_id?: number | null;
  estate_restoration?: string | null;
  restoration_price: number;
  estate_price_with_restoration: number;
  restoration_type?: unknown;
  available_restorations: Record<number, { text?: string }>;
  plan_id: number;
  plan_group?: unknown;
  plan_name: string;
  plan_image: string;
  plan_image_svg?: unknown;
  plan_is_smart: number;
  plan_files_primary_id: number;
  main_plan_file_id: number;
  geo_country: number;
  geo_country_human: string;
  geo_region: number;
  geo_region_human: string;
  geo_city: number;
  geo_city_human: string;
  geo_village?: unknown;
  geo_village_human?: unknown;
  geo_district: number;
  geo_district_human: string;
  geo_complex: number;
  geo_complex_human: string;
  geo_street: number;
  geo_street_human: string;
  geo_house: string;
  geo_house_human: string;
  geo_house_construct: string;
  geo_house_section: string;
  geo_house_entrance: number;
  geo_house_entrance_human: number;
  geo_flatnum: string;
  geo_flatnum_postoffice: string;
  geo_coords: string;
  estate_activity: string;
  estate_ceilingHeight?: unknown;
  estate_ceilingHeight_human: number;
  estate_area: number;
  estate_area_human: string;
  estate_price: number;
  estate_price_human: string;
  estate_price_old?: number | null;
  estate_price_old_human?: string | null;
  estate_currency: string;
  estate_price_m2: number;
  estate_price_m2_human: string;
  estate_rooms: number;
  estate_rooms_human: string;
  estate_studia?: boolean | null;
  estate_apartments?: boolean | null;
  estate_riser: number;
  estate_riser_human: number;
  estate_riserSide?: string | null;
  estate_floor: number;
  estate_floor_human: number;
  estate_floors_in_house: number;
  estate_floors_in_house_human: number;
  estate_floors_in_entrance: number;
  estate_floors_in_entrance_human: number;
  estate_pano?: string | null;
  estate_category: number;
  estate_category_human: string;
  estate_category_type?: unknown;
  estate_category_type_human?: string | null;
  estate_living_new: string;
  estate_private_house_name: string;
  estate_public_house_name: string;
  estate_windowView?: string | null;
  estate_inServiceDate: number;
  estate_inServiceDate_human: string;
  estate_inServiceQuartal: number;
  estate_inServiceQuartal_human: string;
  estate_inServiceMonth: number;
  estate_inServiceMonth_human: string;
  estate_inServiceYear: number;
  estate_inServiceYear_human: number;
  estate_planName: string;
  estate_external_uuid: string;
  estate_flatClass: string;
  estate_levelsCount: number;
  estate_levelsCount_human: number;
  estate_ceilingHeight_flat: number;
  estate_living_house: number;
  estate_living_house_human: string;
  single_contact: number;
  contact_name: string;
  contact_phones: string;
  removed: number;
  custom_attributes: unknown[];
  custom_parent_attributes: unknown[];
  last_record_id?: number;
}
