name: zhk-starter

services:
  postgres:
    image: postgres:17
    container_name: zhk-starter-postgres
    environment:
      POSTGRES_DB: zhk_starter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5441:5432"
    volumes:
      - zhk_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no
    restart: unless-stopped

  imgproxy:
    image: ghcr.io/imgproxy/imgproxy:latest
    container_name: zhk-starter-imgproxy
    ports:
      - "8088:8080"
    environment:
      IMGPROXY_ALLOWED_SOURCES: "https://s3.twcstorage.ru/37651e87-bureau/"
      IMGPROXY_AUTO_WEBP: "true"
      IMGPROXY_AUTO_AVIF: "true"
      IMGPROXY_MAX_SRC_RESOLUTION: "50"
      IMGPROXY_TTL: "2592000"
    restart: unless-stopped

volumes:
  zhk_postgres_data:
